cilium:
  - registry: quay.io
    image: cilium/cilium
  - registry: quay.io
    image: cilium/cilium-envoy
  - registry: quay.io
    image: cilium/operator-generic
  - registry: quay.io
    image: cilium/hubble-relay
  - registry: quay.io
    image: cilium/hubble-ui
  - registry: quay.io
    image: cilium/hubble-ui-backend
