gitlab:
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-webservice-ee
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-sidekiq-ee
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-toolbox-ee
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-workhorse-ee
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitaly
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-shell
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-kas
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-exporter
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/gitlab-base
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/certificates
  - registry: registry.gitlab.com
    image: gitlab-org/gitlab-runner
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/kubectl
  - registry: registry.gitlab.com
    image: gitlab-org/build/cng/cfssl-self-sign
  - registry: registry.gitlab.com
    image: gitlab-org/gitlab-runner/gitlab-runner-helper
    tag: x86_64-v18.11.2
