externalDns:
  - registry: registry.k8s.io
    image: external-dns/external-dns
metricsServer:
  - registry: registry.k8s.io
    image: metrics-server/metrics-server
csiDriverNfs:
  - registry: registry.k8s.io
    image: sig-storage/nfsplugin
  - registry: registry.k8s.io
    image: sig-storage/csi-provisioner
  - registry: registry.k8s.io
    image: sig-storage/csi-resizer
  - registry: registry.k8s.io
    image: sig-storage/csi-snapshotter
  - registry: registry.k8s.io
    image: sig-storage/livenessprobe
  - registry: registry.k8s.io
    image: sig-storage/csi-node-driver-registrar
  - registry: registry.k8s.io
    image: sig-storage/snapshot-controller
