longhorn:
  - registry: docker.io
    image: longhornio/longhorn-manager
  - registry: docker.io
    image: longhornio/longhorn-engine
  - registry: docker.io
    image: longhornio/longhorn-instance-manager
  - registry: docker.io
    image: longhornio/longhorn-share-manager
  - registry: docker.io
    image: longhornio/longhorn-ui
  - registry: docker.io
    image: longhornio/csi-attacher
  - registry: docker.io
    image: longhornio/csi-provisioner
  - registry: docker.io
    image: longhornio/csi-resizer
  - registry: docker.io
    image: longhornio/csi-snapshotter
  - registry: docker.io
    image: longhornio/csi-node-driver-registrar
  - registry: docker.io
    image: longhornio/livenessprobe
  - registry: docker.io
    image: longhornio/backing-image-manager
    tag: v1.11.1
  - registry: docker.io
    image: longhornio/support-bundle-kit
    tag: v0.0.81
