prometheus:
  - registry: quay.io
    image: prometheus/prometheus
  - registry: quay.io
    image: prometheus/alertmanager
  - registry: quay.io
    image: prometheus/node-exporter
prometheusOperator:
  - registry: quay.io
    image: prometheus-operator/prometheus-operator
  - registry: quay.io
    image: prometheus-operator/prometheus-config-reloader
  - registry: quay.io
    image: prometheus-operator/prometheus-config-reloader
  - registry: ghcr.io
    image: jkroepke/kube-webhook-certgen
  - registry: quay.io
    image: thanos/thanos
kubeStateMetrics:
  - registry: registry.k8s.io
    image: kube-state-metrics/kube-state-metrics
grafanaImages:
  - registry: docker.io
    image: grafana/grafana
  - registry: quay.io
    image: kiwigrid/k8s-sidecar
  - registry: docker.io
    image: library/busybox
  - registry: docker.io
    image: bats/bats
alloy:
  - registry: docker.io
    image: grafana/alloy
loki:
  - registry: docker.io
    image: grafana/loki
  - registry: docker.io
    image: nginxinc/nginx-unprivileged
tempo:
  - registry: docker.io
    image: grafana/tempo
beyla:
  - registry: docker.io
    image: grafana/beyla
pyroscope:
  - registry: docker.io
    image: grafana/pyroscope
