stages:
  - test
  - sync

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  SECRET_DETECTION_DISABLED: "false"
  SAST_DISABLED: "false"
  SCAN_KUBERNETES_MANIFESTS: "true"
  BUILDER_IMAGE: "registry.home.mrdvince.me/homelab/builder:1.4.1"

chart-images:
  stage: sync
  image:
    name: $BUILDER_IMAGE
    entrypoint: [""]
  script:
    - sh ci/images.sh chart-pipeline
  artifacts:
    when: always
    paths:
      - imagelist.txt
      - chart-images.yml
    expire_in: 1 week
  rules:
    - if: $SYNC_UPSTREAM_IMAGES == "true"

chart-sync:
  stage: sync
  trigger:
    include:
      - artifact: chart-images.yml
        job: chart-images
    strategy: depend
  needs:
    - chart-images
  rules:
    - if: $SYNC_UPSTREAM_IMAGES == "true"
