stages:
  - test

include:
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml

variables:
  SECRET_DETECTION_DISABLED: "false"
  SAST_DISABLED: "false"
  SCAN_KUBERNETES_MANIFESTS: "true"
