apiVersion: v2
name: bar-assistant
description: Bar Assistant - self-hosted cocktail recipe manager
type: application
version: 0.1.10
appVersion: "5.11.2"

dependencies:
  - name: meilisearch
    version: "0.33.0"
    repository: oci://zot.home.mrdvince.me/helm/upstream/meilisearch
    condition: meilisearch.enabled
