cilium:
  - registry: quay.io
    image: cilium/cilium
    tag: v1.18.6
  - registry: quay.io
    image: cilium/cilium-envoy
    tag: v1.34.10-1762597008-ff7ae7d623be00078865cff1b0672cc5d9bfc6d5
  - registry: quay.io
    image: cilium/operator-generic
    tag: v1.18.6
  - registry: quay.io
    image: cilium/hubble-relay
    tag: v1.18.6
  - registry: quay.io
    image: cilium/hubble-ui
    tag: v0.13.3
  - registry: quay.io
    image: cilium/hubble-ui-backend
    tag: v0.13.3
