externalDns:
  - registry: registry.k8s.io
    image: external-dns/external-dns
    tag: v0.20.0

metricsServer:
  - registry: registry.k8s.io
    image: metrics-server/metrics-server
    tag: v0.8.0
