{
 "title": "OPNSense Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(opnsense_interfaces_received_bytes_total{opnsense_instance=\"opnsense\",interface!=\"LAN\"},interface)"
    }
   },
   {
    "name": "gateway",
    "label": "Gateway",
    "query": {
     "query": "label_values(opnsense_gateways_info{opnsense_instance=\"opnsense\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "uptime",
     "expr": "hrSystemUptime{instance=\"opnsense\",exporter=\"snmp\"} / 100"
    }
   ]
  },
  {
   "title": "Services Status History",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "opnsense_services_status{opnsense_instance=\"opnsense\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "processes",
     "expr": "hrSystemProcesses{instance=\"opnsense\",exporter=\"snmp\"}"
    }
   ]
  },
  { "title": "System Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "CPU Usage",
     "expr": "(100 - ssCpuIdle{instance=\"opnsense\",exporter=\"snmp\"}) / 100"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "legendFormat": "used",
     "expr": "(100 - ssCpuIdle{instance=\"opnsense\",exporter=\"snmp\"}) / 100"
    },
    {
     "legendFormat": "user",
     "expr": "ssCpuUser{instance=\"opnsense\",exporter=\"snmp\"} / 100"
    },
    {
     "legendFormat": "system",
     "expr": "ssCpuSystem{instance=\"opnsense\",exporter=\"snmp\"} / 100"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "load 1m",
     "expr": "laLoadFloat{instance=\"opnsense\",exporter=\"snmp\",laNames=\"Load-1\"}"
    },
    {
     "legendFormat": "load 5m",
     "expr": "laLoadFloat{instance=\"opnsense\",exporter=\"snmp\",laNames=\"Load-5\"}"
    },
    {
     "legendFormat": "load 15m",
     "expr": "laLoadFloat{instance=\"opnsense\",exporter=\"snmp\",laNames=\"Load-15\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "Memory Usage",
     "expr": "((memTotalRealX{instance=\"opnsense\",exporter=\"snmp\"} - memAvailRealX{instance=\"opnsense\",exporter=\"snmp\"}) / memTotalRealX{instance=\"opnsense\",exporter=\"snmp\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "legendFormat": "used",
     "expr": "(memTotalRealX{instance=\"opnsense\",exporter=\"snmp\"} - memAvailRealX{instance=\"opnsense\",exporter=\"snmp\"}) * 1024"
    },
    {
     "legendFormat": "available",
     "expr": "memAvailRealX{instance=\"opnsense\",exporter=\"snmp\"} * 1024"
    },
    {
     "legendFormat": "cached",
     "expr": "memCachedX{instance=\"opnsense\",exporter=\"snmp\"} * 1024"
    },
    {
     "legendFormat": "buffer",
     "expr": "memBufferX{instance=\"opnsense\",exporter=\"snmp\"} * 1024"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "Swap Usage",
     "expr": "((memTotalSwapX{instance=\"opnsense\",exporter=\"snmp\"} - memAvailSwapX{instance=\"opnsense\",exporter=\"snmp\"}) / memTotalSwapX{instance=\"opnsense\",exporter=\"snmp\"}) * 100"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "legendFormat": "used",
     "expr": "((memTotalSwapX{instance=\"opnsense\",exporter=\"snmp\"} - memAvailSwapX{instance=\"opnsense\",exporter=\"snmp\"}) / memTotalSwapX{instance=\"opnsense\",exporter=\"snmp\"}) * 100"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "interrupts",
     "expr": "rate(ssRawInterrupts{instance=\"opnsense\",exporter=\"snmp\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "legendFormat": "context switches",
     "expr": "rate(ssRawContexts{instance=\"opnsense\",exporter=\"snmp\"}[$__rate_interval])"
    }
   ]
  },
  { "title": "Disk & Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Filesystem Utilization",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "legendFormat": "{{hrStorageDescr}}",
     "expr": "100 * hrStorageUsed{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"} / hrStorageSize{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"}"
    }
   ]
  },
  {
   "title": "Storage Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "legendFormat": "{{hrStorageDescr}}",
     "expr": "hrStorageUsed{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"} * hrStorageAllocationUnits{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"}"
    }
   ]
  },
  {
   "title": "Storage Free",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "legendFormat": "{{hrStorageDescr}}",
     "expr": "(hrStorageSize{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"} - hrStorageUsed{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"}) * hrStorageAllocationUnits{instance=\"opnsense\",exporter=\"snmp\",hrStorageType=\"1.3.6.1.2.1.25.2.1.4\",hrStorageDescr=~\"/|/boot/efi|/var/log|/tmp|/home|/zroot\"}"
    }
   ]
  },
  { "title": "Gateway $gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }, "repeat": "gateway" },
  {
   "title": "Gateway Enabled",
   "type": "status-history",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_info{opnsense_instance=\"opnsense\",name=~\"$gateway\",enabled=\"true\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_loss_percentage{opnsense_instance=\"opnsense\",name=~\"$gateway\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RTT (latency)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (name) (opnsense_gateways_rtt_milliseconds{opnsense_instance=\"opnsense\",name=~\"$gateway\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Jitter (RTTd)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(opnsense_gateways_rttd_milliseconds{opnsense_instance=\"opnsense\",name=~\"$gateway\"}[$__rate_interval])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Interfaces",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_received_bytes_total{opnsense_instance=\"opnsense\"}[$__rate_interval])",
     "legendFormat": "RX Rate"
    },
    {
     "expr": "rate(opnsense_interfaces_transmitted_bytes_total{opnsense_instance=\"opnsense\"}[$__rate_interval])\n",
     "legendFormat": "TX Rate"
    },
    {
     "expr": "opnsense_interfaces_input_errors_total{opnsense_instance=\"opnsense\"} + opnsense_interfaces_output_errors_total{opnsense_instance=\"opnsense\"}",
     "legendFormat": "Errors"
    },
    {
     "expr": "opnsense_interfaces_mtu_bytes{opnsense_instance=\"opnsense\"}\n",
     "legendFormat": "MTU"
    }
   ]
  },
  {
   "title": "ARP Table Entries ",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 44 },
   "targets": [
    {
     "expr": "opnsense_arp_table_entries{opnsense_instance=\"opnsense\"}",
     "legendFormat": "{{interface_description}} - {{ip}}"
    }
   ]
  },
  {
   "title": "TCP Connection States",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "opnsense_protocol_tcp_connection_count_by_state{opnsense_instance=\"opnsense\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Received / Transmitted for  $interface",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
   "repeat": "interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(opnsense_interfaces_received_bytes_total{interface=~\"$interface\", opnsense_instance=\"opnsense\"}[$__rate_interval])",
     "legendFormat": "Received Bytes"
    },
    {
     "expr": "-rate(opnsense_interfaces_transmitted_bytes_total{interface=~\"$interface\", opnsense_instance=\"opnsense\"}[$__rate_interval])",
     "legendFormat": "Transmitted Bytes"
    }
   ]
  },
  { "title": "Firewall Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Firewall Statistics by Interface",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"opnsense\"}) / ((sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"opnsense\"}) + sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"opnsense\"})) > 0) * 100",
     "legendFormat": "Passed %"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"opnsense\"}) / ((sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"opnsense\"}) + sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"opnsense\"})) > 0) * 100",
     "legendFormat": "Blocked %"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"opnsense\"})",
     "legendFormat": "Passed"
    },
    {
     "expr": "sum by (interface) (opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"opnsense\"})",
     "legendFormat": "Blocked"
    }
   ]
  },
  {
   "title": "Firewall IPv4 Incoming Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(opnsense_firewall_in_ipv4_pass_packets{opnsense_instance=\"opnsense\"}[$__rate_interval]))",
     "legendFormat": "Pass"
    },
    {
     "expr": "sum(rate(opnsense_firewall_in_ipv4_block_packets{opnsense_instance=\"opnsense\"}[$__rate_interval]))",
     "legendFormat": "Block"
    }
   ]
  },
  {
   "title": "Firewall IPv4 Outgoing Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(opnsense_firewall_out_ipv4_pass_packets{opnsense_instance=\"opnsense\"}[1m]))",
     "legendFormat": "Pass"
    },
    {
     "expr": "sum(rate(opnsense_firewall_out_ipv4_block_packets{opnsense_instance=\"opnsense\"}[1m]))",
     "legendFormat": "Block"
    }
   ]
  }
 ]
}