bookloreImages:
  - registry: ghcr.io
    image: booklore-app/booklore
    tag: "v2.3.1"
  - registry: docker.io
    image: library/mariadb
    tag: "11.4.8@sha256:bc474f00629f0123c10f9e1bca193a45d18af15a274cf0656acda64f1086c3b6"
