.build-images:
  image: registry.home.mrdvince.me/homelab/builder:1.0.0
  services:
    - docker:29-dind
  variables:
    DEST_REGISTRY: registry.home.mrdvince.me
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: "1"
    SEVERITY_THRESHOLD: "CRITICAL,HIGH"
  before_script:
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${DEST_REGISTRY}"
  script:
    - |
      echo "Processing ${BUILD_FILE}..."

      for key in $(yq 'keys | .[]' "${BUILD_FILE}"); do
        image=$(yq ".${key}.image" "${BUILD_FILE}")
        tag=$(yq ".${key}.tag" "${BUILD_FILE}")
        dest="${DEST_REGISTRY}/${image}:${tag}"

        if skopeo inspect --raw "docker://${dest}" >/dev/null 2>&1; then
          echo "Skipping ${image}:${tag}, already exists in registry"
          continue
        fi

        repo=$(yq ".${key}.repo" "${BUILD_FILE}")
        dockerfile=$(yq ".${key}.dockerfile" "${BUILD_FILE}")

        if [ "${repo}" != "null" ]; then
          commit=$(yq ".${key}.commit" "${BUILD_FILE}")
          echo "Building ${image}:${tag} from ${repo}@${commit}"

          git clone "${repo}" /tmp/build
          cd /tmp/build
          git checkout "${commit}"
          build_context="/tmp/build"
          dockerfile_path="/tmp/build/Dockerfile"
        elif [ "${dockerfile}" != "null" ]; then
          echo "Building ${image}:${tag} from local ${dockerfile}"
          build_context="."
          dockerfile_path="${dockerfile}"
        else
          echo "No repo or dockerfile specified for ${key}, skipping"
          continue
        fi

        echo "Scanning source for secrets..."
        trivy fs --scanners secret --exit-code 1 "${build_context}" || {
          echo "Secrets found in source, aborting"
          exit 1
        }

        echo "Building image..."
        docker build -t "${dest}" -f "${dockerfile_path}" "${build_context}"

        echo "Scanning image for vulnerabilities..."
        trivy image --exit-code 1 --severity "${SEVERITY_THRESHOLD}" "${dest}" || {
          echo "Critical/High vulnerabilities found, aborting"
          exit 1
        }

        echo "Pushing image..."
        docker push "${dest}"

        echo "Successfully built and pushed ${image}:${tag}"

        if [ "${repo}" != "null" ]; then
          cd -
          rm -rf /tmp/build
        fi
      done
