.build-images:
  image: registry.home.mrdvince.me/homelab/builder:1.0.0
  services:
    - name: docker:29-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DEST_REGISTRY: registry.home.mrdvince.me
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
    DOCKER_BUILDKIT: "1"
  before_script:
    - |
      echo "Waiting for docker daemon..."
      for i in $(seq 1 30); do
        if docker info >/dev/null 2>&1; then
          echo "Docker daemon ready"
          break
        fi
        sleep 2
      done
    - docker login -u "${REGISTRY_USER}" -p "${REGISTRY_PASSWORD}" "${DEST_REGISTRY}"
  script:
    - |
      echo "Processing ${BUILD_FILE}..."

      for key in $(yq 'keys | .[]' "${BUILD_FILE}"); do
        image=$(yq ".${key}.image" "${BUILD_FILE}")
        tag=$(yq ".${key}.tag" "${BUILD_FILE}")
        dest="${DEST_REGISTRY}/${image}:${tag}"

        if skopeo inspect --raw "docker://${dest}" >/dev/null 2>&1; then
          echo "Skipping ${image}:${tag}, already exists in registry"
          continue
        fi

        repo=$(yq ".${key}.repo" "${BUILD_FILE}")
        dockerfile=$(yq ".${key}.dockerfile" "${BUILD_FILE}")

        original_dir=$(pwd)

        if [ "${repo}" != "null" ]; then
          commit=$(yq ".${key}.commit" "${BUILD_FILE}")
          echo "Building ${image}:${tag} from ${repo}@${commit}"

          git clone "${repo}" /tmp/build
          cd /tmp/build
          git checkout "${commit}"
          build_context="/tmp/build"

          if [ "${dockerfile}" != "null" ]; then
            dockerfile_path="${original_dir}/${dockerfile}"
          else
            dockerfile_path="/tmp/build/Dockerfile"
          fi
        elif [ "${dockerfile}" != "null" ]; then
          echo "Building ${image}:${tag} from local ${dockerfile}"
          build_context="."
          dockerfile_path="${dockerfile}"
        else
          echo "No repo or dockerfile specified for ${key}, skipping"
          continue
        fi

        echo "Scanning source for secrets..."
        trivy fs --scanners secret --exit-code 1 "${build_context}" || {
          echo "Secrets found in source, aborting"
          exit 1
        }

        echo "Building image..."
        docker build -t "${dest}" -f "${dockerfile_path}" "${build_context}"

        echo "Scanning image for vulnerabilities..."
        trivy image --severity HIGH,CRITICAL "${dest}"

        trivy image --exit-code 1 --severity CRITICAL "${dest}" || {
          echo "CRITICAL vulnerabilities found, aborting"
          exit 1
        }

        echo "Pushing image..."
        docker push "${dest}"

        echo "Successfully built and pushed ${image}:${tag}"

        if [ "${repo}" != "null" ]; then
          cd -
          rm -rf /tmp/build
        fi
      done
