def safe-image-name [image: string] {
  $image
  | str replace -r '@sha256:' '-sha256-'
  | str replace -a -r '[^[:alnum:]]' '-'
  | str replace -a -r '--+' '-'
  | str replace -r '^-|-$' ''
  | str substring 0..95
}

def build-rules [row: record] {
  [
    {if: '$BUILD_IMAGES == "true"'}
    {if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /build-all/'}
    {
      if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: [
        $row.source_file
        $row.dockerfile
      ]
    }
  ]
}

def sync-rules [category: string, source_files: list<string>] {
  let force_variable = if $category == chart {
    '$SYNC_UPSTREAM_IMAGES == "true"'
  } else {
    '$SYNC_LOCAL_IMAGES == "true"'
  }
  let category_paths = if $category == chart {
    let chart_paths = (
      $source_files
      | each {|path| $"($path | path dirname)/**/*" }
    )
    [$chart_paths infrastructure/images/config.yaml] | flatten | uniq | sort
  } else {
    $source_files | uniq | sort
  }

  [
    {if: $force_variable}
    {
      if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      changes: $category_paths
    }
  ]
}

def build-job [row: record] {
  {
    name: $"build:($row.name)"
    value: {
      extends: .build-image
      variables: {BUILD_NAME: $row.name}
      rules: (build-rules $row)
    }
  }
}

def sync-jobs [category: string, rows: list<record>] {
  $rows
  | group-by image
  | transpose image rows
  | sort-by image
  | each {|group|
      let job_name = $"sync:($category):(safe-image-name $group.image)"
      let sources = ($group.rows | get source_file | uniq | sort)

      {
        name: $job_name
        value: {
          extends: .sync-image
          variables: {IMAGE_TO_SYNC: $group.image}
          rules: (sync-rules $category $sources)
        }
      }
    }
}

def jobs-to-record [jobs: list<record>] {
  let names = ($jobs | get name)
  if (($names | uniq | length) != ($names | length)) {
    let duplicates = (
      $names
      | group-by
      | transpose name values
      | where {|row| ($row.values | length) > 1 }
      | get name
      | str join ", "
    )
    error make {msg: $"generated CI job names are not unique: ($duplicates)"}
  }

  $jobs | reduce -f {} {|job, result| $result | insert $job.name $job.value }
}

export def pipeline-record [
  builds: list<record>
  charts: list<record>
  locals: list<record>
] {
  let build_jobs = ($builds | sort-by name | each {|row| build-job $row })
  let chart_jobs = (sync-jobs chart $charts)
  let local_jobs = (sync-jobs local $locals)

  let jobs = ([$build_jobs $chart_jobs $local_jobs] | flatten)
  jobs-to-record $jobs
}

export def generated-ci-content [
  cfg: record
  builds: list<record>
  charts: list<record>
  locals: list<record>
] {
  let header = "# generated by `nu ci/images.nu generate-ci`; do not edit by hand\n"
  let yaml = (pipeline-record $builds $charts $locals | to yaml)
  $header + $yaml
}

export def write-generated-ci [
  cfg: record
  builds: list<record>
  charts: list<record>
  locals: list<record>
] {
  generated-ci-content $cfg $builds $charts $locals | save -f $cfg.generated_ci
}

export def verify-generated-ci [
  cfg: record
  builds: list<record>
  charts: list<record>
  locals: list<record>
] {
  if not ($cfg.generated_ci | path exists) {
    error make {msg: $"generated CI file is missing: ($cfg.generated_ci)"}
  }

  let expected = (generated-ci-content $cfg $builds $charts $locals)
  let actual = (open --raw $cfg.generated_ci)

  if $actual != $expected {
    error make {msg: $"generated CI is stale; run `nu ci/images.nu generate-ci`"}
  }

  print "generated image CI is current"
}
