{
 "title": "Proxmox via Prometheus",
 "description": "Proxmox Virtual Environment Dashboard",
 "tags": [
  "Proxmox",
  "Prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "collector", "query": "elysium" },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(pve_node_info{instance=\"$instance\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resource allocation summary",
   "type": "table",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (id, name, type, node) (pve_guest_info{instance=\"$instance\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (id) (pve_up{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (id) (pve_cpu_usage_limit{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (id) (pve_memory_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (id) ((pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes{instance=\"$instance\"}) and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\", template!=\"1\"} and on (id, instance) pve_up{instance=\"$instance\"} == 1)"
    },
    {
     "expr": "sum by (id) (pve_disk_size_bytes{instance=\"$instance\"} and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\"})"
    },
    {
     "expr": "sum by (id) ((pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"}) and on (id, instance) pve_guest_info{instance=\"$instance\", node=~\"$node\", type=\"lxc\"})"
    }
   ]
  },
  {
   "title": "CPU history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "pve_cpu_usage_limit{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current CPU",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit{instance=\"$instance\"}) * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_cpu_usage_limit{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "pve_memory_size_bytes{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes{instance=\"$instance\"}) * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pve_memory_usage_bytes{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(pve_memory_size_bytes{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"})",
     "legendFormat": "total"
    },
    {
     "expr": "sum(pve_memory_size_bytes{instance=\"$instance\"} * on(id, instance) group_left(name) pve_node_info{instance=\"$instance\", name=~\"$node\"})",
     "legendFormat": "total for max"
    }
   ]
  },
  {
   "title": "Guests CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_cpu_usage_ratio{instance=\"$instance\"} / pve_cpu_usage_limit{instance=\"$instance\"}) * on(id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\"}) and on(id, instance) pve_up{instance=\"$instance\"} == 1",
     "legendFormat": "{{node}} / {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Guests memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((pve_memory_usage_bytes{instance=\"$instance\"} / pve_memory_size_bytes{instance=\"$instance\"}) * on(id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\"}) and on(id, instance) pve_up{instance=\"$instance\"} == 1",
     "legendFormat": "{{node}} / {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Storage usage",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes{instance=\"$instance\", id=~\"storage/.+\"} / pve_disk_size_bytes{instance=\"$instance\"}) * on (id, instance) group_left(node, storage, plugintype, content) pve_storage_info{instance=\"$instance\", node=~\"$node\"}",
     "legendFormat": "{{node}} / {{storage}}"
    }
   ]
  },
  {
   "title": "LXC guests Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(pve_disk_usage_bytes{instance=\"$instance\"} / pve_disk_size_bytes{instance=\"$instance\"}) * on (id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\", type=\"lxc\"}",
     "legendFormat": "{{node}} / {{name}} ({{type}})"
    }
   ]
  },
  {
   "title": "Network IO/s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(rate(pve_network_receive_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\"}) and on(id, instance) pve_up{instance=\"$instance\"} == 1",
     "legendFormat": "{{node}} / {{name}} RECV ({{type}})"
    },
    {
     "expr": "(rate(pve_network_transmit_bytes{instance=\"$instance\"}[5m]) * on(id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\"}) and on(id, instance) pve_up{instance=\"$instance\"} == 1",
     "legendFormat": "{{node}} / {{name}} SEND ({{type}})"
    }
   ]
  },
  {
   "title": "Disk IO/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "((rate(pve_disk_write_bytes{instance=\"$instance\"}[5m]) + rate(pve_disk_read_bytes{instance=\"$instance\"}[5m])) * on(id, instance) group_left(name, type, node) pve_guest_info{instance=\"$instance\", node=~\"$node\"}) and on(id, instance) pve_up{instance=\"$instance\"} == 1",
     "legendFormat": "{{node}} / {{name}} ({{type}})"
    }
   ]
  }
 ]
}